### ISSUE TITLE
Error trying to connect to Redis

### ISSUE THREAD

**Issue by supercodepoet** [phoenixframework/phoenix_pubsub_redis#19]
Seeing this error:

```
** (EXIT) shutdown: failed to start child: Phoenix.PubSub.Redis
        ** (EXIT) an exception was raised:
            ** (BadFunctionError) expected a function, got: [fastlane: Phoenix.Channel.Server, pool_size: 1, name: FontawesomeCdn.PubSub, adapter: Phoenix.PubSub.Redis, host: "localhost"]
                (elixir) lib/keyword.ex:608: Keyword.do_merge/5
                (phoenix_pubsub_redis) lib/phoenix_pubsub_redis/redis.ex:56: Phoenix.PubSub.Redis.init/1
                (stdlib) supervisor.erl:287: :supervisor.init/1
                (stdlib) gen_server.erl:328: :gen_server.init_it/6
                (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
Anyone else experiencing this? 

Looks like it might be related to these lines in redis.ex

```elixir
    opts = handle_url_opts(opts)
    |> Keyword.merge(@defaults, opts)
```

From what I have read merge/3 expects a function not a Keyword, correct?

**Comment by mitchellhenke** [comment]
yep, that's definitely not right, thanks for the report.  I will have a fix here shortly.
